# Generated by Django 5.1.3 on 2026-02-17 13:21

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('father_first_name', models.CharField(max_length=300)),
                ('father_last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('father_contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('father_nic', models.CharField(blank=True, max_length=300, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mother_contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('mother_nic', models.CharField(blank=True, max_length=300, null=True)),
                ('is_father_applicable', models.BooleanField(default=True)),
                ('is_mother_applicable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=300, null=True)),
                ('board_name', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('program', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_campaign')],
            },
        ),
        migrations.CreateModel(
            name='FollowUpType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('integrate_with_google_calendar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_followup_type')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_id', models.UUIDField(db_index=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=300)),
                ('created_by', models.UUIDField(db_index=True)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('country_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('state_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('city_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('nic', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=300, null=True)),
                ('remarks', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.contact')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by', models.UUIDField(db_index=True)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('follow_up_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.followuptype')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('file', models.JSONField(max_length=500)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.medium'),
        ),
        migrations.CreateModel(
            name='PreRequisiteCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=300, null=True)),
                ('max_marks', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
                ('marks_in_percentage', models.BooleanField()),
                ('is_mandatory', models.BooleanField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.prerequisite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_source')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.source'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('priority', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(default='open')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_business_stage')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stage'),
        ),
        migrations.CreateModel(
            name='StageReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StageReasonEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('created_by', models.UUIDField(db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stage')),
                ('stage_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stagereason')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_tag')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.tag'),
        ),
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('model_id', models.UUIDField()),
                ('model_type', models.CharField(max_length=300)),
                ('user_id', models.UUIDField(db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='stagereason',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_stage_reason'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user_id')},
        ),
    ]
