# Generated by Django 5.1.3 on 2026-01-26 08:14

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_id', models.UUIDField(db_index=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by', models.UUIDField(db_index=True)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('priority', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('previous_education', models.CharField(blank=True, max_length=300, null=True)),
                ('p_name', models.CharField(blank=True, max_length=300, null=True)),
                ('p_contact_number', models.CharField(blank=True, max_length=25, null=True)),
                ('p_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=300, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_followup_type')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('follow_up_by', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.followuptype')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('path', models.TextField(max_length=500)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_lost_reason')],
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.medium'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_source')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.source'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('priority', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(default='open')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_business_stage')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stage'),
        ),
        migrations.CreateModel(
            name='StageReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField(max_length=500)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('reason_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lostreason')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.stage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', unique_with=['business_id'])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug', 'business_id'), name='unique_slug_per_business_tag')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.tag'),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('model_id', models.UUIDField()),
                ('model_type', models.PositiveSmallIntegerField()),
                ('user_id', models.UUIDField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
