# Generated by Django 5.1.3 on 2026-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='class_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
