# Generated by Django 5.1.3 on 2026-02-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leads.team'),
        ),
    ]
