# Generated by Django 5.1.3 on 2026-02-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_contact_father_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.contact'),
        ),
    ]
