# Generated by Django 5.1.3 on 2026-02-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_institute_remove_prerequisite_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='encrypted_business_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='prerequisitecourse',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='leads.prerequisite'),
        ),
    ]
