# Generated by Django 5.1.3 on 2026-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_source_encrypted_business_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
