# Generated by Django 5.1.3 on 2026-02-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='encrypted_business_id',
        ),
    ]
