# Generated by Django 5.1.3 on 2026-02-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_type', to='leads.followuptype'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='leads.lead'),
        ),
    ]
