# Generated by Django 5.1.3 on 2026-03-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_source_encrypted_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='leads.lead'),
        ),
    ]
