# Generated by Django 5.1.3 on 2026-03-17 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('leads', '0007_alter_followup_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object id')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='model name')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=10, verbose_name='action')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='changes')),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='business id')),
                ('auth_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='auth id')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business_id', 'timestamp'], name='activity_lo_busines_3022e3_idx'), models.Index(fields=['auth_id', 'timestamp'], name='activity_lo_auth_id_7964b9_idx'), models.Index(fields=['model_name', 'timestamp'], name='activity_lo_model_n_254ea8_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_c82b76_idx')],
            },
        ),
    ]
