# Generated by Django 5.1.3 on 2026-04-25 14:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('branch_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('target', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
