# Generated by Django 5.1.3 on 2026-04-30 06:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_sessiontarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recipients', models.JSONField()),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
