# Generated by Django 5.1.3 on 2026-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_quickemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
