# Generated by Django 5.1.3 on 2026-05-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
