# Generated by Django 5.1.3 on 2026-05-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_team_branch_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['priority']},
        ),
    ]
