# Generated by Django 5.1.3 on 2026-05-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_stage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagereason',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_reasons', to='leads.stage'),
        ),
    ]
