# Generated by Django 5.1.3 on 2026-05-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_stagereason_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='stage_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='leads.stagereasonentry'),
        ),
    ]
