# Generated by Django 5.1.3 on 2026-05-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_tracking_stage_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='stage_reason',
            new_name='stage_reason_entry',
        ),
    ]
