# Generated by Django 5.1.3 on 2026-05-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_rename_stage_reason_tracking_stage_reason_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-updated_at']},
        ),
    ]
