LEAD_VIEW_ALL="lead-view-all"
LEAD_MODIFY_ALL="lead-modify-all"
LEAD_BRANCH_WISE="branch-wise-leads"
LEAD_READ="lead-read"
CAMPAIGN_VIEW_ALL="campaign-view-all"
CAMPAIGN_MODIFY_ALL="campaign-modify-all"
REPORT_EXPORT_VIEW_ALL="report-export-view-all"
SESSION_TARGET_BRANCH_WISE="branch-wise-session-target"
