# String Lengths
CHAR_LENGTH = 300
LONG_CHAR_LENGTH = 500
EMAIL_LENGTH = 250
PHONE_LENGTH = 25
TEXT_LENGTH = 800
IMAGE_URL_LENGTH = 1000
LONG_TEXT_LENGTH = 2000
DECIMAL_LENGTH = 10
DECIMAL_PLACES_LENGTH = 2

# Module Types
STAGE = 1
MEDIUM = 2
SOURCE = 3
TAG = 4
BRANCH = 5

OPEN = "open"
WON = "won"
LOST = "lost"
