# Generated by Django 5.1.3 on 2026-02-26 15:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('app_slug', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'report_export',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['app_slug'], name='idx_app_slug')],
            },
        ),
    ]
