# Generated by Django 5.1.3 on 2026-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
