# Generated by Django 5.1.3 on 2026-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_export', '0002_export_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='format_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
