# Generated by Django 5.1.3 on 2025-02-13 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('request_method', models.CharField(blank=True, max_length=300, null=True)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access_control.module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.UUIDField(db_index=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.permission')),
            ],
        ),
    ]
