# Generated by Django 5.1.3 on 2025-03-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['sort_order']},
        ),
    ]
