# Generated by Django 5.1.3 on 2025-03-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_permission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
