# Generated by Django 5.1.3 on 2025-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_alter_module_created_at_alter_module_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='frontend_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
