# Generated by Django 5.1.3 on 2025-06-23 11:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_permission_frontend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
