# Generated by Django 5.1.3 on 2025-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_module_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
