# Generated by Django 5.1.3 on 2025-07-31 11:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_module_updated_at_alter_permission_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
