# Generated by Django 5.1.3 on 2025-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='app_slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='app_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
